### ISSUE TITLE
Update Role names in areas that check for role permissions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#102]
I changed some of the role names a while ago so they need to be updated in the code.

For instance, if you do !welcome @user123556 it doesn't allow any mods to do so.

**Comment by Coolguy3289** [comment]
I don't know about the current config on the server. But the default config doesn't have the moderation roles. Will update it in the latest PR. This happens because the bot can only look for a Role by name, not a roleID, so it is a fluid search and can fail if the name changes.

**Comment by Coolguy3289** [comment]
I also think that the moderation section of the config needs updated to reflect the new role system implemented by Brazen

**Comment by Coolguy3289** [comment]
Fixed in: https://github.com/lbryio/lbry-wunderbot/pull/148

**Comment by Coolguy3289** [comment]
@filipnyquist Please Merge and Close the PR associated with this issue and close this issue after

**Comment by Coolguy3289** [comment]
This can be closed now
