### ISSUE TITLE
Improve welcome message system

### ISSUE THREAD

**Issue by jsnfwlr** [lbryio/lbry-wunderbot#104]
Right now, blasting a new user with 5 messages as soon as they join seems to be something that would overwhelm most people.

It may be better to revise this down to one or two messages with better wording to reduce the wall of text they get, and then some interactive triggers (possibly via reaction to the initial welcome) that triggers further messages.

If we stop using the embedded messages and use regular messages, the lines won't get wrapped in that short little box either.

If the bot reacts to it's own messages first, the reaction buttons are already in place for the user to click.

:oncoming_police_car: = Show Ground Rules 
:moneybag: = Show tip/wallet/exchange help
:white_check_mark: Get verified
:clapper: = Show how to contribute content
:computer: = Show how dev's can help out
:lips: = Show info about spee.ch
:green_book: = Show info about FAQ

**Comment by tzarebczan** [comment]
@MSFTserver  / @Coolguy3289 interested in working on this?

**Comment by Coolguy3289** [comment]
I will look into the concept of a bot seeing a reaction as an event. If that exists, it should make things much easier.

**Comment by MSFTserver** [comment]
ot exists and since its going to be dm only kinda thing itll be really easy to detect what is emjoi is doubled up when they click one

**Comment by Coolguy3289** [comment]
Well yeah. I've just never looked into reaction events till now

**Comment by Coolguy3289** [comment]
I am currently working on the reaction system. Will keep you guys posted as progress ensues.

**Comment by Coolguy3289** [comment]
#141 is my current hangup

**Comment by Coolguy3289** [comment]
Another thing to consider, the Emojis to be used are fairly standard. So it has to be decided out of the default emojis that come with discord, which ones associate with it's intended message. @tzarebczan Can you compile a list of Discord standard emoji's that you want associated with each message so that I have some realistic emoji's to work with?

**Comment by Coolguy3289** [comment]
Closed until further notice.
