### ISSUE TITLE
recognize ! commands in line text

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#108]
We should be able to write something like
"Can you send me your !logfile ?" and it calls the command

**Comment by nikooo777** [comment]
[this addresses it](https://github.com/nikooo777/lbry-wunderbot/commit/df8258ea7526d5911243f159b3a5183c6ee382cb)

**Comment by MSFTserver** [comment]
shouldnt something like that be made in bot.js or one of the helpers so it can work for all commands?

**Comment by nikooo777** [comment]
I wouldn't want some commands to be triggered mid sentence i think.

My solution takes that into account. However if I'm going down this road i might actually think of porting over the config file in mongo so that we don't have to change the code every time we want to remove or add a command.

**Comment by nikooo777** [comment]
#116 is my solution
I also made it case insensitive
