### ISSUE TITLE
Use explorer api for supply calls

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#110]
We should use this for LBC supply calls. Would it be possible to get it scheduled or not allow it to run the api each time stats is called?

https://explorer.lbry.io/api/v1/supply

**Comment by MSFTserver** [comment]
its not even loading for me right now....

**Comment by MSFTserver** [comment]
never mind it just takes like atleast a minute for the link to reply you sure you want that

**Comment by tzarebczan** [comment]
Yea, that's why I don't want it run often.. A schedule would be best.

**Comment by MSFTserver** [comment]
![image](https://user-images.githubusercontent.com/18357967/33916152-43094e5e-df5c-11e7-8165-9d6f2a456980.png)
this is awefully  long for an API to reply

**Comment by MSFTserver** [comment]
yea i havent learned how to use cache in javascript yet so @filipnyquist or @nikooo777 would have to implement that

**Comment by tzarebczan** [comment]
It runs a lbrycrd command which adds up all the unspent outputs to get the total supply.

**Comment by MSFTserver** [comment]
well if its tied to lbrycrd isn't tipbot or claimbot where ever they run have that running we could transfer it there and use the same method but a lot faster not 1 minute response times like trying to call the endpoint

**Comment by Coolguy3289** [comment]
@tzarebczan Is this still something that is being pursued? Does anyone have an answer to @MSFTserver's question?

**Comment by tzarebczan** [comment]
Now that CMC is using that endpoint, we don't need to do this anymore.
