### ISSUE TITLE
Tipbot does not reply to commands in DM

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#113]
When I message tipbot with !tip deposit or !tip help (From #bot-sandbox), I don't get a response. Another user complained about this as well. 

Can someone take a look into this?

**Comment by filipnyquist** [comment]
@nikooo777 could you take a look at this? you should have access to the server.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry-tipbot #6](https://github.com/lbryio/lbry-tipbot/issues/6) via [**ZenHub**](https://www.zenhub.com/)
