### ISSUE TITLE
line length is too short

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-wunderbot#119]
The current line length set by prettier is 80 (as per default).
I believe we all have monitors wide enough to handle more than 80 chars.

To make the code more readable I'd suggest increasing the line length to 140. I tried this on a local branch and the code looks much cleaner without all those lines breaking every word.

Anyone against this? If you're in favor just thumbs up this message (let's avoid flooding our mailboxes for a simple issue)

If nobody is against this I will make a separate PR correcting the code.

tagging mainly @MSFTserver @filipnyquist

**Comment by vfioox** [comment]
Hello, on the new bot version the line length will be set to 120 characters!

**Comment by filipnyquist** [comment]
@vfioox is correct! The new wunderbot Will have longer line length.

**Comment by Coolguy3289** [comment]
New length has been addressed in #151
