### ISSUE TITLE
Run bot stats commands in #Discord-Stats channel daily

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#145]
Would like to run the following commands daily at midnight EST in #Discord-Stats channel:
<>totalusers
<>activeusers
<>totalmessages
<>messagemin

**Comment by kauffj** [comment]
Should this be synced to metabase as well?

**Comment by filipnyquist** [comment]
@kauffj this data is avaible in a mysql database FYI

**Comment by tzarebczan** [comment]
@filipnyquist Can we get the role bot on the wunderbot server?  Then we can setup access to the mysql database. 

I'm still looking forward to your new bot and maybe a stats module when the time comes :)

**Comment by filipnyquist** [comment]
@tzarebczan i´ll move over the bot to the wunderbot server, want mysql db to be there or any other place? Yes, i also look forward to it, home the whole next week so great things to come ;)

**Comment by nikooo777** [comment]
what's the progress on this?
Should I take a look myself?

**Comment by tzarebczan** [comment]
We added the SQL database to metabase, so we have the data available. A single dashboard was created, we'll look into more.

I don't think we need to run this is in Discord anymore since we have the data available.
