### ISSUE TITLE
Claimbot - don't show thumbnail/images for NSFW content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#150]
Recently a claim showed up in the #content channel which had an NSFW thumbnail. In that case, the claim wasn't marked as NSFW, but this brings up a good point - we should not show thumbnails for claims marked NSFW.

**Comment by nikooo777** [comment]
this should be an easy change.

**Comment by nikooo777** [comment]
you almost got me there. I checked and I indeed had implemented that already. https://github.com/lbryio/lbry-wunderbot/blob/master/bot/modules/claimbot.js#L252

is that not working?

**Comment by tzarebczan** [comment]
Didn't know it was implemented, cool! The recent example was not marked
properly.

**Comment by Coolguy3289** [comment]
Closing this issue, as it seems to be resolved.
