### ISSUE TITLE
Use Channel Name for Author

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-wunderbot#152]
Instead of calling the `author `of all spee.ch files `Spee.ch` use the `Channel Name`

![image](https://user-images.githubusercontent.com/29914179/38129240-90f3b638-3441-11e8-9ef0-bd106173207f.png)

**Comment by tzarebczan** [comment]
Related to https://github.com/lbryio/lbry-wunderbot/issues/97 - we don't currently have the channel information available on the content bot - it needs to be decoded from the claim information.

**Comment by filipnyquist** [comment]
This can be added when chainquery gets added to the bot!

**Comment by filipnyquist** [comment]
Fixed in #210
