### ISSUE TITLE
Allow Any Case with roles

### ISSUE THREAD

**Issue by Coolguy3289** [lbryio/lbry-wunderbot#160]
Currently, you have to match the case of the role in the config exactly, else the command fails as it doesn't find the role. I'd like to implement a way for the bot to recognize the roles no matter the case of the letters.

**Comment by nikooo777** [comment]
check this out: https://github.com/lbryio/lbry-wunderbot/blob/master/bot/modules/commandsV2.js#L39

**Comment by Coolguy3289** [comment]
I'll look into it. I also need to add the ability to add All roles, so maybe have aliases with the roles in the config and if more than one role has the same alias, it adds them all.
