### ISSUE TITLE
Allow assignment of LBRYian role

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#165]
Currently, you only get the LBRYian role if you self assign one of the other roles. This role should also be allowed to self assign. I can so someone wanted to be part of the community category without assigning of of the current roles.

**Comment by nikooo777** [comment]
Is this still relevant? I am not sure I understand it right, do we want it to be so that all new users are automatically assigned that role?

**Comment by Coolguy3289** [comment]
I understand the issue. Tom wants it so that you can JUST add the LBRYian role by itself, without basically being forced to add another role. It's an easy addition, and I can tackle it in a few minutes worth of work.

**Comment by nikooo777** [comment]
thanks you for tackling this
