### ISSUE TITLE
Channnel ID must be updated on Welcome.Js 

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-wunderbot#167]
Several Random User receive message for enable Direct Message . and I saw 2 invalid channel on the message. im sure it should replace with #bot-sandbox and #welcome-to-lbry channel. to make this message Perfect. 
![screenshot_2018-05-17-20-36-50-733](https://user-images.githubusercontent.com/26609573/40181178-ad637f46-5a12-11e8-8687-fe7ae52fc281.jpeg)
i think welcome.js on line 24 must be updated with latest channel ID and its can be found on discord webhook on server setting page. Thanks

**Comment by ICTman1076** [comment]
Perhaps issue should be closed now, if there aren't any further problems?
