### ISSUE TITLE
Wunderbot ignoring commands from some people.

### ISSUE THREAD

**Issue by filipnyquist** [lbryio/lbry-wunderbot#173]
Right now wunderbot seems to ignore commands from random people. This needs to get checked more.
Making this issue so we can get to the bottom of this.

**Comment by Coolguy3289** [comment]
This seems to be partially caused by an update to Node on the server box

**Comment by nikooo777** [comment]
i'd call it more a "lack" of correctness in code. Undeclared vars shouldn't be used.
let's try to address this without downgrading node

**Comment by filipnyquist** [comment]
Correct, i'll get them patched asap when i get home

**Comment by filipnyquist** [comment]
This has now been fixed!
