### ISSUE TITLE
!stats and !hash commands not working on LBRY Discord Server

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-wunderbot#179]
please see #market-and-trading channel
julie and btzr trying to input key !stats but not working
![image](https://user-images.githubusercontent.com/26609573/40796017-edfeb2a2-652d-11e8-9d21-8f66d1c62b16.png)
on #mining the code !hash working but i saw error code like this screenshot
![image](https://user-images.githubusercontent.com/26609573/40796036-f804bc74-652d-11e8-8e8c-c1b759e94900.png)

**Comment by filipnyquist** [comment]
Both are now working!
