### ISSUE TITLE
Feature Request : Integrate Chainquery to Wunderbot

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-wunderbot#190]
LBRY now have chainquery technology. and it means will improve LBRY to the next generation of content sharing platform. would be nice if this feature will be integrated to wunderbot by type commands !chainquery <channel name> . this is my ideas and i hope wunderbot have this feature to make community happiness . thanks

**Comment by tzarebczan** [comment]
Great idea :)
We could do something like !topbid one

or !communitybids to list all of em

or !topbids to list top 10 claims

or !topchannels to list top 10 channels

**Comment by filipnyquist** [comment]
I was actually planning to integrate it in the upcoming version of
wunderbot! Great idea!

**Comment by filipnyquist** [comment]
@tiger5226 i think some queries for showing top channels and claims could be a good way to start this, chainquery in wunderbot would show the whole community the power of it!
