### ISSUE TITLE
Content bot - add claim id to content URL

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#192]
The current content URL doesn't have the claim ID, so it may open to the vanity claim and not the claim that was posted.

**Comment by filipnyquist** [comment]
This will be fixed in the new wunderbot, which integrates chainquery instead of the decoder, which allows us to get this data on the fly.

**Comment by filipnyquist** [comment]
I´ll take a look and see if I can get a fix going for it with the current version in this upcoming sprint.
