### ISSUE TITLE
Linker removes - from URL

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#202]
Looks like `-` is removed from linked URLS:

THX1342 - Yesterday at 11:15 PM
I put a claim higher than the existing (0,01) for lbry://minecraft-in-real-life-the-flash. Why is my content not appearing there (yes... I'm running tests to try and understand how LBRY works)
LBRY WunderbotBOT - Yesterday at 11:15 PM

LBRY Linker
I see you tried to post a LBRY URL, here's a friendly hyperlink to share and for others to access your content with a single click: 
https://open.lbry.io/minecraftinreallifetheflash.

**Comment by filipnyquist** [comment]
As a quick fix, I´ll add the lbrylinker code from the new wunderbot, which handles this better and cleaner.

**Comment by filipnyquist** [comment]
Solved in #203
