### ISSUE TITLE
claim bot issues - takeover time support

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#212]
1) Rename author to channel, make @channel clickable via open.lbry.io
2) Check bid amount - support bids less than 2 decimals, see below
3) Estimated takeover block used to show for vanity URL takeovers - do we have this data from chainquery? 

```
New claim from @thomaszarebczan
lbry://@thomaszarebczan/1
Title
test subs1
Author
@thomaszarebczan
License
None
Claimed for
0.00 LBC

Block 424215 • Claim ID 9fe87d00de19fff14168473b341c88e69a38aa87 • Data from Chainquery
```
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by filipnyquist** [comment]
Discord embeds does not allow links in the embed so can´t link the channel, we have the takeover added, i can add the takeover block as a field if wanted. bid amount is easily fixed.

**Comment by filipnyquist** [comment]
The takeover block will be showed with an approx time if the takeover block is not the same as the current block.

**Comment by tzarebczan** [comment]
I dont' think the takeover time is showing...see below for a claim on lbry://five (I'd assume it wouldn't take the channel into account)

![image](https://user-images.githubusercontent.com/8120721/45691471-bd119e80-bb26-11e8-8cc3-fe3724ae1591.png)

**Comment by alyssaoc** [comment]
closing for now, reopen in needed
