### ISSUE TITLE
Putting an lbry URL in your message in back ticks causes the wunderbot to generate bad URLs

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-wunderbot#217]
If you type a message such as:

_An example is \`lbry://ten\` or \`lbry://eight\`._

This results in Wunderbot generating urls like:

https://open.lbry.io/ten%60
and
https://open.lbry.io/eight%60

I think it would probably be better for it to completely ignore these instead.

**Comment by 42degrees** [comment]
![image](https://user-images.githubusercontent.com/1676142/45726346-0e984880-bb7c-11e8-9498-7fd238ee4dc9.png)
An example screen shot.

**Comment by nikooo777** [comment]
a solution could be to use a regex to grab the whole valid name.

**Comment by MSFTserver** [comment]
@nikooo777 line 17 in lbrylink
new regex will exclude ending ` id also add other chars you know wont work
```
/\bhttps?:\/\/\S+[^`]/gi
```

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nikooo777** [comment]
rather than being exclusive it should probably be inclusive of all the accepted chars. because i could be adding another random char that isn't valid and you'd have the same problem I think.
http://beta.lbry.tech/resources/uri

**Comment by 42degrees** [comment]
I'm haven't been using Discord very long, but I had been given the impression that the way to keep Discord from processing something was to surround it with backticks.  Is that not also true for the bots?

**Comment by MSFTserver** [comment]
backticks just create code blocks

**Comment by MSFTserver** [comment]
putting links inside angle brackets prevents discord from displaying meta data thats all i know so like <https://lbry.io> wouldnt show meta data at end of the message thats the only way i know of any discord ingoring

**Comment by 42degrees** [comment]
@MSFTserver Thanks, I didn't know that.  I'll do that from now on.

**Comment by nikooo777** [comment]
fixed
