### ISSUE TITLE
Wunderbot URL Confusion 

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-wunderbot#223]
Wonderbot gets confused when 2 URL's are added when on is a LBRY URL and one isn't.

![image](https://user-images.githubusercontent.com/29914179/47920553-0adb3e00-defe-11e8-9595-2eb0278d34d8.png)

**Comment by nikooo777** [comment]
this issue is related to https://github.com/lbryio/lbry-wunderbot/issues/217 (bad parsing of the URL). I'll tackle that soon.
