### ISSUE TITLE
Wunderbot error on !addrole and !delrole in DM

### ISSUE THREAD

**Issue by zxawry** [lbryio/lbry-wunderbot#228]
Wunderbot throws this error when !addrole or !delrole are used in DM:

![20190119_201653](https://user-images.githubusercontent.com/15372952/51430307-49d18380-1c11-11e9-94b9-5acf381349df.png)

`msg` does not have `guild` property if it's issued from DM.
https://github.com/lbryio/lbry-wunderbot/blob/101ccf10a7e2eca90e7ee053cef779650ef15711/bot/modules/rolesetter.js#L17-L18

**Comment by tzarebczan** [comment]
Thanks for filing!!

**Comment by Coolguy3289** [comment]
This error is intentional, as the bot can be in multiple discord servers and won't be able to differentiate which server you may be trying to add a role to. Without another optional argument to dictate the guild you are talking about, this isn't something to "fix", rather than another feature.

**Comment by MSFTserver** [comment]
@coolguy3289 just add
 `let inPrivate = require('../helpers.js').inPrivate;`
and
```
if (inPrivate(msg)) {
msg.channel.send('You Can Not set roles In DMs!');
return;
}
```

**Comment by nikooo777** [comment]
@Coolguy3289 wanna tackle this?
