### ISSUE TITLE
Add a Testnet faucet command

### ISSUE THREAD

**Issue by binaryflesh** [lbryio/lbry-wunderbot#232]
As a curious end user, I think it would be very convenient if there was functionality to request testnet credits every 24 hours. I think a gentle reminder after a week to send back the credits would be a engaging and fun way to encourage more lbrycrdd users.

**Comment by tzarebczan** [comment]
@binaryflesh, thanks for opening this. We have a developer program at LBRY.tech which offers free LBC to active GitHub members.

We also have a way to setup your own local LBRY network to control/spend/reset as you like in regnet mode - https://lbry.tech/resources/regtest-setup (needs updating though!!)

I think either of those are better than the testnet scenario. @nikooo777 thoughts?

**Comment by binaryflesh** [comment]
I opened [lbry.tech#268](https://github.com/lbryio/lbry.tech/issues/268) and [lbrycrd#261](https://github.com/lbryio/lbrycrd/issues/261). I was unaware of how -Regtest was supposed to be used with `lbrycrdd` and how it compared to using testnet. Closing this one out
