### ISSUE TITLE
Start with !why

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-wunderbot#245]
It seems a lot of questions and comments start from poor assumptions about why LBRY is a good choice.

a !why should be the best response to some people.

**Comment by Coolguy3289** [comment]
@jessopb If you write up a quick blurb for the command, I'll toss that into the code!

**Comment by ICTman1076** [comment]
Thought I'd write something up quick for this. Based it mostly off the FAQ. I'll happily make any changes you may want

**Comment by Coolguy3289** [comment]
Being addressed in https://github.com/lbryio/lbry-wunderbot/pull/262

**Comment by jessopb** [comment]
Sorry @Coolguy3289 I missed this.
