### ISSUE TITLE
Multi language welcome message

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-wunderbot#249]
I think with Discord api we might be able to have welcome message get send to user in language used by user.
https://discordapp.com/developers/docs/resources/user#usernames-and-nicknames

Example:
```{
  "id": "80351110224678912",
  "username": "Nelly",
  "discriminator": "1337",
  "avatar": "8342729096ea3675442027381ff50dfe",
  "verified": true,
  "email": "nelly@discordapp.com",
  "flags": 64,
  "locale": Polish,
  "premium_type": 1
}```
"locale": Polish, will trigger wunderbot to send welcome message in Polish language :)

**Comment by nikooo777** [comment]
thank you for opening this issue.
I support the community writing this feature, it could be an interesting addition if it's just for the welcome message :)

**Comment by ICTman1076** [comment]
Unfortunately this is not currently possible. Discord.js does not allow you to see any user's locale (except your own), probably because Discord itself doesn't let bots see user's locale.

**Comment by drdrjojo** [comment]
locale is only available through oauth2 authentication and not for the bots directly

**Comment by Coolguy3289** [comment]
Unless you make it a reaction based welcome message, and the reaction chosen will send a welcome message in the language choice of the user

**Comment by littlemadhatter** [comment]
Vote to close, welcome command not used anymore and might be taken out
