### ISSUE TITLE
Obsolete API

### ISSUE THREAD

**Issue by danger89** [lbryio/lbry-wunderbot#250]
Keep in mind the following CoinMarketCap API is obsolete and needs to be replaced asap.
https://github.com/lbryio/lbry-wunderbot/blob/master/bot/modules/stats.js#L11

Regards,
Melroy

**Comment by danger89** [comment]
Ps. also with the basic (free) plan of CoinMarketCap with the new API you don't get OHLCV data :-1:

**Comment by tzarebczan** [comment]
Thanks for opening the issue @danger89 . Would you be interested in making the change? We can help get the api key for us if needed.

**Comment by tmlee** [comment]
Hi guys, i would suggest that you take a look at the CoinGecko API over at https://www.coingecko.com/api

No keys required and we may have some data points that you are looking for. Happy to answer any questions you may have!

**Comment by nikooo777** [comment]
We could replace it with coingecko as suggested, here is the endpoint we'd want to use:
https://api.coingecko.com/api/v3/coins/lbry-credits?localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false

**Comment by danger89** [comment]
See example in the LBRY Telegram bot:
https://gitlab.melroy.org/melroy/lbry-bot/blob/master/src/exchange.js

**Comment by danger89** [comment]
@tzarebczan 
Its October. So I will pick this up! Could you add `hacktoberfest` label?

**Comment by Coolguy3289** [comment]
Would you be converting to CoinGecko? Or updating new coincapmarket?

**Comment by danger89** [comment]
CoinGecko is fine by me :)

**Comment by Coolguy3289** [comment]
Niko already gave the greenlight on the API move. So it's all yours :)

**Comment by ykris45** [comment]
Close close close.  hehehe

**Comment by danger89** [comment]
ow its done already :\ Thx

**Comment by nikooo777** [comment]
thank you all for your interest, please make sure you (all) state when you're working on an issue or otherwise we end up with twice the effort, which is unfortunate.
