### ISSUE TITLE
Get rid of all the "vars" in the code

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-wunderbot#261]
This codebase has seen contributions from a lot of people. 
As a consequence it's not very clean and doesn't often follow the right standards.
A good first issue would be to go through the code and get rid of all the `var` declarations.

Read about `var` vs `let` here:
https://codeburst.io/difference-between-let-and-var-in-javascript-537410b2d707

This is obviously not just a search and replace task, it requires a slight understanding of the surrounding code as restricting the scope of variables previously unscoped could lead to errors.

As a tip I'd suggest using smart IDEs like Webstorm. IDEs should always help you in figuring out mistakes in the code.

**Comment by nikooo777** [comment]
Alright I transferred the issue, this one is definitely valid for this repo (tipbot used to be part of wunderbot in the past).
If you're interested in working on it, it's a very valid issue here

**Comment by Coolguy3289** [comment]
Pretty sure we did a code clean up here as well a while ago. Don't quote me on that

**Comment by Excolo** [comment]
@haichuan0424 Did you start cleaning? Otherwise, I'd like to give it a go.

**Comment by haichuan0424** [comment]
@Excolo I'd like to work on this one if you don't mind. 
@nikooo777 Thanks for letting me know. I have started with this one.
