### ISSUE TITLE
Why does the bot say "Please set your Discord Presence to Online to talk to the bot!"

### ISSUE THREAD

**Issue by Yamboy1** [lbryio/lbry-wunderbot#289]
I don't see any reason why the user's presence would affect anything, and it can get spammy if you're not set to online.
![Screenshot_20191228_211605](https://user-images.githubusercontent.com/37413895/71541008-65afde80-29b7-11ea-8e2b-4203ac69e5f1.png)

**Comment by Coolguy3289** [comment]
This was implemented because a null value being returned while looking up the user id. At the time of implementation, this was a bug in DiscordJS and the only fix at the time was to send that message if a command was received from a user with an offline status.

**Comment by Coolguy3289** [comment]
This has been removed in #290
