### ISSUE TITLE
!Stats not working in discord

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-wunderbot#45]
I input !stats but it does not work in #market-and-trading or #bot-sandbox on our new server discord. can it be in switch from old slack to new discord #

> bug

**Comment by MSFTserver** [comment]
there is no command for stats

**Comment by MSFTserver** [comment]
not a bug just not there

**Comment by MSFTserver** [comment]
i told you earlier ill be porting that today sometime

**Comment by ykris45** [comment]
Im sorry. Hehe not there i mean.

**Comment by MSFTserver** [comment]
@ykris45 you can close this if you want it will be ready by the end of tomorrow

**Comment by MSFTserver** [comment]
https://github.com/lbryio/lbry-wunderbot/pull/49

**Comment by ykris45** [comment]
Calm down bro. Im close it today. Becsuse yesterday im weekend bro. Seems busy right now

**Comment by MSFTserver** [comment]
i am calm lol there was no need to even open this issue in the first place, if you looked at the bot youd notice it wasnt added yet

**Comment by MSFTserver** [comment]
just have some patience
