### ISSUE TITLE
Doesn't include transaction fee when determining available funds

### ISSUE THREAD

**Issue by flungo** [lbryio/lbry-wunderbot#5]
When making a withdrawal, you are able to withdraw your entire balance. Since withdrawal amounts are given pre-fee and this is what is used to validate, if you withdraw your entire balance, the transaction is accepted and you end up having a negative balance.

When this occurs an error should be provided with the maximum that can be withdrawn from the wallet accounting for the fee that will be added - this will allow the user to enter the correct amount to withdraw all their funds, if this is what they would like to do.

**Comment by lyoshenka** [comment]
wunderbot uses accounts in lbrycrdd to track balances. There's a known bug in here (inherited from bitcoin) that allows an account to go negative. See https://github.com/bitcoin/bitcoin/issues/2079

You're correct about what the solution is, but to be honest, it's more work than its worth. We don't mind paying the transaction fee in this case. 

If you'd like to fix this, we're always happy to accept PRs :smile:
