### ISSUE TITLE
Wunderbot leaves Negative balance after W/d

### ISSUE THREAD

**Issue by CjMapope** [lbryio/lbry-wunderbot#6]
Wunderbot dosen't take the withdrawal fee from the users balance, but as the network still needs the fee, the user is left with a slight negative balance after said withdrawal :/
Better way, or "working as intended" ?
https://cloud.githubusercontent.com/assets/12862793/25199996/024533b8-250a-11e7-8fc3-00589c342b70.PNG

**Comment by filipnyquist** [comment]
As of now this is not a priority, but if i get any spare time i could prob look into it!

**Comment by kauffj** [comment]
@filipnyquist agreed this isn't a huge issue, but it is real, so we should probably leave it open?

**Comment by kauffj** [comment]
Or merge this into #5 and reopen that one if you like that one more :P

**Comment by lyoshenka** [comment]
This is the same issue as #5
