### ISSUE TITLE
tipbot should be separated from wunderbot

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-wunderbot#69]
I think it's bad practice to keep the tipbot in the same repository as wunderbot by just having a separate branch. 
I believe it's best to have its own repository as the development of the branches will never meet again. 
What do you think? I created a separated repo and pushed the code to it, if you guys agree i'd transfer the ownership to lbryio.

https://github.com/nikooo777/lbry-tipbot

**Comment by kauffj** [comment]
@nikooo777 what's the fundamental reason the bots can't share the same code-base or the branches won't meet again? Is it just to keep the potentially more sensitive code separate?

**Comment by nikooo777** [comment]
Yes I think that the tipbot is slightly more sensitive than the other bots and for the sake of simplicity I would keep it in a different project.

On the other hand, other people might be interested in using the tipbot without having to pick it from our moderation bots.

Separating it would make it easier for us to fork, change, deploy; without dealing with branches.

**Comment by kauffj** [comment]
:+1: from me, it's obviously insanity to use different branches for this :)

**Comment by nikooo777** [comment]
code was pushed to https://github.com/lbryio/lbry-tipbot

we should now delete the branches and the now-irrelevant code from this repository.
@filipnyquist perhaps you can help me with a low priority this or next week?
I'll be first working on the content bot

**Comment by MSFTserver** [comment]
@nikooo777 @Coolguy3289 PR #47 has started working on removing this

**Comment by Coolguy3289** [comment]
It is removed in my PR already. I'm just finishing with the help command then it will be finished.

**Comment by filipnyquist** [comment]
Has been moved to the lbry-tipbot repo!
