### ISSUE TITLE
Irc bridge to #lbry on freenode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#70]
A couple users in the past have requested an IRC bridge.

**Comment by aayanl** [comment]
I can host a bridge https://github.com/42wim/matterbridge , I already do it for another discord I'm a part of.

**Comment by MSFTserver** [comment]
i dont think we are worried about having a place to host it, we just need the bridge part, and i would prefer if we included with wunderbot and not another bot that just starts to bulk things up we really dont need

**Comment by MSFTserver** [comment]
i was looking into that see if i could port it over to wunderbot custom function, be my guest if you wanna give it a shot

**Comment by MSFTserver** [comment]
i figured we use a nice nom package or i could work off one from the github repo of the npm package

**Comment by tzarebczan** [comment]
I know @filipnyquist had some ideas here, not sure which route he wanted to go.

**Comment by filipnyquist** [comment]
@tzarebczan @MSFTserver I have a working plugin for this, just need to make some small changes, i´ll get it added tonight after i´ve checked the other PRs

**Comment by tzarebczan** [comment]
@filipnyquist can you look to see what happened with the irc bridge? I think it went down a while ago.

**Comment by filipnyquist** [comment]
I´ll take a look right now!

**Comment by Coolguy3289** [comment]
What ever happened with this?

**Comment by filipnyquist** [comment]
We have had a few requests to get this added again, therefore i'll add this under this sprint.

**Comment by filipnyquist** [comment]
Found the problem with the old IRC integration, as we are using Amazon I needed to tell Freenode that we are a legit client by using SASL. This bridge is now online in #shared on discord and #lbry on freenode.
