### ISSUE TITLE
the bot crashes when a bot sends a message

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-wunderbot#90]
Whenever a bot sends a message, the bot itself crashes because it tires to access a property that doesn't exist when it's the bot itself writing the message.

```
    if (
      inPrivate(msg) ||
      hasPerms(msg) ||
      msg.author.bot ||
      hasExcludedSpamChannels(msg) ||
      hasExcludedSpamUsers(msg)
    )
```

should be changed to

```
    if (
      inPrivate(msg) ||
      msg.author.bot ||
      hasPerms(msg) ||
      hasExcludedSpamChannels(msg) ||
      hasExcludedSpamUsers(msg)
    )
```

**Comment by MSFTserver** [comment]
what file is this?

**Comment by MSFTserver** [comment]
cant seem to duplicate the bot crashing

**Comment by filipnyquist** [comment]
@MSFTserver the spam checker, gets this error because of hasPerms being called before checking if its a bot, therefore if its a bot it crashed because a bot is not a member

**Comment by MSFTserver** [comment]
oh maybe cause i had role BOTS added to has perms ;)
