### ISSUE TITLE
the code is hard to edit without getting conflicts

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-wunderbot#92]
People should be aware that we're using prettier to format the code now.

I am getting several conflicts every time i try to merge some changes, therefore the code should be cleaned and everyone else should run `yarn precommit` or equivalent before pushing code.

I suggest we don't accept pull requests that don't come in formatted

**Comment by nikooo777** [comment]
keeping this open for a while so that people can see it

**Comment by MSFTserver** [comment]
ill start doing this now 👍

**Comment by tzarebczan** [comment]
Does this affect code changes being pushed through github's web interface?

**Comment by Coolguy3289** [comment]
That's how I run my PRs since I can't push from IntelliJ.

**Comment by Coolguy3289** [comment]
I've run the precommit on Rolesetter, as of the last PR, that is now uniform with any other modules that have run Prettier.
