### ISSUE TITLE
Content Bot - add channel to claim URL hyperlink name / URL 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#97]
If content is posted under a channel, it should show the URL as lbry://@jiggytom#232131231231231/claimname 

actual example from recent content post: 
lbry://@humblegoddess#7d00b2935e6f508bf5e2cbef609571f96495bedb/twitchstream91120171

**Comment by tzarebczan** [comment]
@nikooo777 is aware of this one and it requires some type of decoding of claim data. 

From Jack:
jack [2:56 PM] 
not without building lbryschema into lbrycrd to decode them
[2:56] 
lbrycrd returns protobuf claims as some kind of escaped unicode (edited)
jack
[2:58 PM] 
it probably wouldnt be terribly difficult to include lbryschema.go for decoding/validating them to json text (edited)

**Comment by filipnyquist** [comment]
I have a feeling chainquery could work some magic for the claimbot @tiger5226

**Comment by tiger5226** [comment]
yeah [chainquery](https://github.com/lbryio/chainquery) can provide the decoded json data of a claim or channel. For example [@fillerino](https://chainquery.lbry.io/api/sql?query=SELECT%20name,%20claim_id,%20value_as_json%20FROM%20claim%20WHERE%20name%20=%20%22@fillerino%22)

**Comment by filipnyquist** [comment]
@tzarebczan The example you posted doesn't work, it just redirects me to the channel. Is this correct?

**Comment by filipnyquist** [comment]
Fixed in #210
