### ISSUE TITLE
Content Bot - show claim amount

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#98]
@nikooo777 Is it possible to show the claim amount on the bid?

**Comment by nikooo777** [comment]
it's most likely possible however it can't be done without calling an extra RPC method.
Is that really necessary and worth looking into?
unfortunately claims don't carry the amount property

**Comment by Coolguy3289** [comment]
@tzarebczan Is this still something that you want looked into? Just cleaning up issues that have been opened for a while.

**Comment by tzarebczan** [comment]
@Coolguy3289 yes, but it sounds like it would require some claim decoding that's not being done currently.

**Comment by nikooo777** [comment]
this could become much easier with chainquery!

**Comment by filipnyquist** [comment]
Can be added when chainquery gets integrated!
