### ISSUE TITLE
Claimbot - Show only Claims, Channels and updates

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#99]
Claimbot should only show any new claims/channels created as well as any updates to either. 

current issues:
1) It's not showing new channels created (the old claimbot did)
2) It's showing claims that received supports/tips (see #content from 10:04 EST / 10:10 EST - support and then tip - unbubbled / unbubbled1-1 respectively)

**Comment by tzarebczan** [comment]
@nikooo777 did you get a chance to look into this?

**Comment by nikooo777** [comment]
thank you for pinging me, no i didn't. I'll make sure to do that ASAP
